<?php

namespace ContainerTPeUtlN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bhte3RAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bhte3RA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bhte3RA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.Yq7tqo_', 'get_ServiceLocator_Yq7tqoService', true],
            'App\\Controller\\PDFController::index' => ['privates', '.service_locator.lr6LYlL', 'get_ServiceLocator_Lr6LYlLService', true],
            'App\\Controller\\PostsController::index' => ['privates', '.service_locator.nBxFRYb', 'get_ServiceLocator_NBxFRYbService', true],
            'App\\Controller\\PostsController::misPosts' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostsController::verPosts' => ['privates', '.service_locator.Yq7tqo_', 'get_ServiceLocator_Yq7tqoService', true],
            'App\\Controller\\PostsCrudController::delete' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\PostsCrudController::edit' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\PostsCrudController::index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsCrudController::new' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsCrudController::show' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\RegistroController::index' => ['privates', '.service_locator.Ct0feJ7', 'get_ServiceLocator_Ct0feJ7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserCrudController::delete' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserCrudController::edit' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserCrudController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController::new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController::pdf' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.Yq7tqo_', 'get_ServiceLocator_Yq7tqoService', true],
            'App\\Controller\\PDFController:index' => ['privates', '.service_locator.lr6LYlL', 'get_ServiceLocator_Lr6LYlLService', true],
            'App\\Controller\\PostsController:index' => ['privates', '.service_locator.nBxFRYb', 'get_ServiceLocator_NBxFRYbService', true],
            'App\\Controller\\PostsController:misPosts' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostsController:verPosts' => ['privates', '.service_locator.Yq7tqo_', 'get_ServiceLocator_Yq7tqoService', true],
            'App\\Controller\\PostsCrudController:delete' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\PostsCrudController:edit' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\PostsCrudController:index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsCrudController:new' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsCrudController:show' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\RegistroController:index' => ['privates', '.service_locator.Ct0feJ7', 'get_ServiceLocator_Ct0feJ7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserCrudController:delete' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserCrudController:edit' => ['privates', '.service_locator.4MF6DUv', 'get_ServiceLocator_4MF6DUvService', true],
            'App\\Controller\\UserCrudController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController:new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController:pdf' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserCrudController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\PDFController::index' => '?',
            'App\\Controller\\PostsController::index' => '?',
            'App\\Controller\\PostsController::misPosts' => '?',
            'App\\Controller\\PostsController::verPosts' => '?',
            'App\\Controller\\PostsCrudController::delete' => '?',
            'App\\Controller\\PostsCrudController::edit' => '?',
            'App\\Controller\\PostsCrudController::index' => '?',
            'App\\Controller\\PostsCrudController::new' => '?',
            'App\\Controller\\PostsCrudController::show' => '?',
            'App\\Controller\\RegistroController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserCrudController::delete' => '?',
            'App\\Controller\\UserCrudController::edit' => '?',
            'App\\Controller\\UserCrudController::index' => '?',
            'App\\Controller\\UserCrudController::new' => '?',
            'App\\Controller\\UserCrudController::pdf' => '?',
            'App\\Controller\\UserCrudController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\PDFController:index' => '?',
            'App\\Controller\\PostsController:index' => '?',
            'App\\Controller\\PostsController:misPosts' => '?',
            'App\\Controller\\PostsController:verPosts' => '?',
            'App\\Controller\\PostsCrudController:delete' => '?',
            'App\\Controller\\PostsCrudController:edit' => '?',
            'App\\Controller\\PostsCrudController:index' => '?',
            'App\\Controller\\PostsCrudController:new' => '?',
            'App\\Controller\\PostsCrudController:show' => '?',
            'App\\Controller\\RegistroController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserCrudController:delete' => '?',
            'App\\Controller\\UserCrudController:edit' => '?',
            'App\\Controller\\UserCrudController:index' => '?',
            'App\\Controller\\UserCrudController:new' => '?',
            'App\\Controller\\UserCrudController:pdf' => '?',
            'App\\Controller\\UserCrudController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
