<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTPeUtlN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTPeUtlN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTPeUtlN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTPeUtlN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTPeUtlN\App_KernelDevDebugContainer([
    'container.build_hash' => 'TPeUtlN',
    'container.build_id' => '03b16148',
    'container.build_time' => 1653817934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTPeUtlN');
